//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp7.Models
{
    using System;
    
    public partial class UserList_Result1
    {
        public string Login { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
    }
}
