//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Table
    {
        public int Id { get; set; }
        [DisplayName("Login")]
        [Required(ErrorMessage = "Pole jest wymagane!")]
        [DataType(DataType.Text)]
        public string login { get; set; }

        [DisplayName("Has≥o")]
        [Required(ErrorMessage = "Pole jest wymagane!")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [DisplayName("Potwierdü Has≥o")]
        [Required(ErrorMessage = "Pole jest wymagane!")]
        [DataType(DataType.Password)]
        [Compare("password")]
        public string confirmpassword { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Pole jest wymagane!")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
    }
}
