//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp7.Models
{
    using System;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UserDataEntities : DbContext
    {
        public UserDataEntities()
            : base("name=UserDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table> Table { get; set; }
    
        public virtual int InsertUserData(string login, string email, string password)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUserData", loginParameter, emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<UserListing_Result> UserListing()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserListing_Result>("UserListing");
        }
    
        public virtual ObjectResult<Nullable<int>> isLoginExist(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("isLoginExist", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<InputUserData> IsLogin(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InputUserData>("IsLogin", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CheckLogin(string lOGIN, string pASSWORD)
        {
            var lOGINParameter = lOGIN != null ?
                new ObjectParameter("LOGIN", lOGIN) :
                new ObjectParameter("LOGIN", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CheckLogin", lOGINParameter, pASSWORDParameter);
        }
    
        public virtual int DeleteUser(string lOGIN)
        {
            var lOGINParameter = lOGIN != null ?
                new ObjectParameter("LOGIN", lOGIN) :
                new ObjectParameter("LOGIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUser", lOGINParameter);
        }
    }
}
